ignore gh stuff

diff --git a/.github/workflows/sequential-cd-workflow-composite.yml b/.github/workflows/sequential-cd-workflow-composite.yml
--- a/.github/workflows/sequential-cd-workflow-composite.yml
+++ b/.github/workflows/sequential-cd-workflow-composite.yml
@@ -79,7 +79,6 @@ jobs:
       deploy_test: ${{ steps.evaluate_scope.outputs.deploy_test }}
       deploy_prod: ${{ steps.evaluate_scope.outputs.deploy_prod }}
       source_branch: ${{ steps.evaluate_scope.outputs.source_branch }} # New output
-      is_main_pipeline: ${{ steps.evaluate_scope.outputs.is_main_pipeline }}
       artifact_name: ${{ github.event.inputs.source_artifact_name }}
       db_migration_project_path: ${{ github.event.inputs.db_migration_project_path }}
     steps:
@@ -97,15 +96,9 @@ jobs:
           DEPLOY_TEST="false"
           DEPLOY_PROD="false"
 
-          IS_MAIN_PIPELINE="false"
-          if [[ "$ARTIFACT_NAME" == release-* ]]; then
-            IS_MAIN_PIPELINE="true"
-          fi
-
           echo "Deployment Scope: $DEPLOYMENT_SCOPE"
           echo "Source Run ID: $SOURCE_RUN_ID"
           echo "Artifact: $ARTIFACT_NAME"
-          echo "Is Main Pipeline: $IS_MAIN_PIPELINE"
 
           case "$DEPLOYMENT_SCOPE" in
             dev)
@@ -134,18 +127,17 @@ jobs:
           esac
 
           # Fetch source branch using GitHub API
-          SOURCE_BRANCH=$(gh api /repos/${{ github.repository }}/actions/runs/$SOURCE_RUN_ID | jq -r '.head_branch')
-          if [ -z "$SOURCE_BRANCH" ] || [ "$SOURCE_BRANCH" == "null" ] || [ "$SOURCE_BRANCH" == "" ]; then
-            echo "::error::Could not determine source branch for run ID $SOURCE_RUN_ID. Received: '$SOURCE_BRANCH'"
-            exit 1
-          fi
-          echo "Source Branch: $SOURCE_BRANCH"
-          echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
+          # SOURCE_BRANCH=$(gh api /repos/${{ github.repository }}/actions/runs/$SOURCE_RUN_ID | jq -r '.head_branch')
+          # if [ -z "$SOURCE_BRANCH" ] || [ "$SOURCE_BRANCH" == "null" ] || [ "$SOURCE_BRANCH" == "" ]; then
+          #   echo "::error::Could not determine source branch for run ID $SOURCE_RUN_ID. Received: '$SOURCE_BRANCH'"
+          #   exit 1
+          # fi
+          # echo "Source Branch: $SOURCE_BRANCH"
+          # echo "source_branch=$SOURCE_BRANCH" >> $GITHUB_OUTPUT
 
           echo "deploy_dev=$DEPLOY_DEV" >> $GITHUB_OUTPUT
           echo "deploy_test=$DEPLOY_TEST" >> $GITHUB_OUTPUT
           echo "deploy_prod=$DEPLOY_PROD" >> $GITHUB_OUTPUT
-          echo "is_main_pipeline=$IS_MAIN_PIPELINE" >> $GITHUB_OUTPUT
 
           echo "Will deploy to DEV: $DEPLOY_DEV"
           echo "Will deploy to TEST: $DEPLOY_TEST"
